"""
Module 5: 轴文重构与字幕生成
将 Module 3 的时间轴与 Module 4 的清洗文本重新对齐，生成 SRT/ASS 字幕。
"""
import argparse
import json
import sys
from pathlib import Path
from datetime import timedelta

# -------------------------------
# 说话人样式配置（未来可移至 config.py，与 M3 共用）
# -------------------------------
ASS_SPEAKER_COLORS = {
    "SPEAKER_00": ("Speaker0", "&H0000FF00"),
    "SPEAKER_01": ("Speaker1", "&H00FF0000"),
    "SPEAKER_02": ("Speaker2", "&H000000FF"),
    "SPEAKER_03": ("Speaker3", "&H00FFFF00"),
    "SPEAKER_04": ("Speaker4", "&H00FF00FF"),
    "SPEAKER_05": ("Speaker5", "&H0000FFFF"),
    "SPEAKER_06": ("Speaker6", "&H00FF8000"),
    "SPEAKER_07": ("Speaker7", "&H008000FF"),
}
FALLBACK_STYLE = ("Default", "&H00FFFFFF")


def report_progress(percent: float, message: str = ""):
    sys.stderr.write(f"PROGRESS: {percent:.1f}% {message}\n")
    sys.stderr.flush()


def load_json(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)


def save_text(filepath, text):
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(text)


def format_timestamp_srt(seconds):
    t = timedelta(seconds=seconds)
    total_secs = int(t.total_seconds())
    ms = t.microseconds // 1000
    h = total_secs // 3600
    m = (total_secs % 3600) // 60
    s = total_secs % 60
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def format_timestamp_ass(seconds):
    t = timedelta(seconds=seconds)
    total_secs = int(t.total_seconds())
    cs = t.microseconds // 10000
    h = total_secs // 3600
    m = (total_secs % 3600) // 60
    s = total_secs % 60
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def build_srt(subtitle_entries):
    lines = []
    for i, entry in enumerate(subtitle_entries, 1):
        start_str = format_timestamp_srt(entry["start"])
        end_str = format_timestamp_srt(entry["end"])
        text = entry["text"]
        speaker = entry.get("speaker", "")
        if speaker and speaker != "UNKNOWN":
            text = f"[{speaker}] {text}"
        lines.append(f"{i}")
        lines.append(f"{start_str} --> {end_str}")
        lines.append(text)
        lines.append("")
    return "\n".join(lines)


def build_ass(subtitle_entries, title="Generated by AI"):
    # 动态生成样式表头部
    header = f"""[Script Info]
Title: {title}
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1
"""
    # 动态添加说话人样式（基于 ASS_SPEAKER_COLORS）
    for speaker_id, (style_name, color) in ASS_SPEAKER_COLORS.items():
        header += f"Style: {style_name},Arial,20,{color},&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n"

    header += """
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    # 建立扬声器到样式名的映射
    style_map = {}
    for speaker_id, (style_name, _) in ASS_SPEAKER_COLORS.items():
        style_map[speaker_id] = style_name

    lines = [header]
    for entry in subtitle_entries:
        start_str = format_timestamp_ass(entry["start"])
        end_str = format_timestamp_ass(entry["end"])
        text = entry["text"].replace("\n", "\\N")
        speaker = entry.get("speaker", "")
        style = style_map.get(speaker, FALLBACK_STYLE[0])
        speaker_label = speaker.replace("_", " ") if speaker and speaker != "UNKNOWN" else ""
        if speaker_label:
            text = f"{speaker_label}: {text}"
        lines.append(f"Dialogue: 0,{start_str},{end_str},{style},,0,0,0,,{text}")
    return "\n".join(lines)


def align_and_rebuild(
    raw_json_path,
    cleaned_json_path,
    output_dir,
    output_format="ass",
    min_duration=0.5,
    speaker_names=None,
    verbose=True,
):
    """
    核心对齐与生成逻辑。
    """
    raw_data = load_json(raw_json_path)
    cleaned_data = load_json(cleaned_json_path)

    if not raw_data or not cleaned_data:
        raise ValueError("输入 JSON 为空")

    report_progress(10.0, "对齐时间轴...")

    use_index = all("original_index" in seg for seg in cleaned_data)

    if use_index:
        # 为 raw_data 添加临时索引
        for i, seg in enumerate(raw_data):
            seg["__temp_idx"] = i

        subtitle_entries = []
        # 按 original_index 分组，每组内按文本长度比例分配原始片段的时间
        from collections import defaultdict
        groups = defaultdict(list)
        for seg in cleaned_data:
            groups[seg["original_index"]].append(seg)

        for orig_idx, grp in groups.items():
            if orig_idx >= len(raw_data):
                if verbose:
                    print(f"[警告] original_index={orig_idx} 超出 raw_data 范围 (0-{len(raw_data)-1})，已跳过 {len(grp)} 条")
                continue
            raw_seg = raw_data[orig_idx]
            start = raw_seg["start"]
            end = raw_seg["end"]
            duration = end - start
            total_text_len = sum(len(s["text"]) for s in grp)
            if total_text_len == 0:
                continue
            cum_ratio = 0
            for seg in grp:
                text_len = len(seg["text"])
                ratio = text_len / total_text_len
                seg_start = start + cum_ratio * duration
                seg_end = seg_start + ratio * duration
                # 防止浮点误差溢出
                seg_start = max(start, min(seg_start, end))
                seg_end = max(start, min(seg_end, end))
                entry = {
                    "start": seg_start,
                    "end": seg_end,
                    "text": seg["text"],
                    "speaker": seg.get("speaker", raw_seg.get("speaker", "UNKNOWN")),
                }
                subtitle_entries.append(entry)
                cum_ratio += ratio
    else:
        if verbose:
            print("[警告] 清洗数据未包含 original_index，使用顺序匹配。")
        subtitle_entries = []
        for raw, clean in zip(raw_data, cleaned_data):
            text = clean.get("text", "")
            if not text:
                continue
            entry = {
                "start": raw["start"],
                "end": raw["end"],
                "text": text,
                "speaker": clean.get("speaker", raw.get("speaker", "UNKNOWN")),
            }
            subtitle_entries.append(entry)

    report_progress(50.0, "过滤短片段...")
    if min_duration > 0:
        subtitle_entries = [
            e for e in subtitle_entries if (e["end"] - e["start"]) >= min_duration
        ]

    # 替换说话人名称
    if speaker_names:
        mapping = {}
        if isinstance(speaker_names, str):
            pairs = [p.strip() for p in speaker_names.split(",")]
            for pair in pairs:
                if ":" in pair:
                    key, val = pair.split(":", 1)
                    mapping[key.strip()] = val.strip()
        elif isinstance(speaker_names, dict):
            mapping = speaker_names
        for entry in subtitle_entries:
            spk = entry.get("speaker", "")
            if spk in mapping:
                entry["speaker"] = mapping[spk]

    # 生成文件
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    base_name = Path(raw_json_path).stem
    if output_format == "srt":
        content = build_srt(subtitle_entries)
        ext = "srt"
    else:
        content = build_ass(subtitle_entries)
        ext = "ass"
    out_path = out_dir / f"{base_name}.{ext}"
    report_progress(80.0, f"写入 {ext.upper()} ...")
    save_text(out_path, content)
    report_progress(100.0, "完成")
    if verbose:
        print(f"[Module 5] 字幕已生成: {out_path} (共 {len(subtitle_entries)} 条)")
    return out_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Module 5: 轴文重构与字幕生成")
    parser.add_argument("raw", help="原始 ASR JSON (Module 3 输出)")
    parser.add_argument("cleaned", help="清洗后文本 JSON (Module 4 输出)")
    parser.add_argument("-o", "--output-dir", default="../subtitles",
                        help="字幕输出文件夹 (默认: ../subtitles)")
    parser.add_argument("--format", choices=["srt", "ass"], default="ass",
                        help="输出格式 (默认: ass)")
    parser.add_argument("--min-duration", type=float, default=0.5,
                        help="过滤小于此秒数的片段 (默认: 0.5)")
    parser.add_argument("--speaker-names", default=None,
                        help="说话人名称映射，如 'SPEAKER_00:Alice, SPEAKER_01:Bob'")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    try:
        align_and_rebuild(
            raw_json_path=args.raw,
            cleaned_json_path=args.cleaned,
            output_dir=args.output_dir,
            output_format=args.format,
            min_duration=args.min_duration,
            speaker_names=args.speaker_names,
            verbose=not args.quiet,
        )
    except Exception as e:
        print(f"失败: {e}", file=sys.stderr)
        sys.exit(1)